// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251118005311_AddScrumModels")]
    partial class AddScrumModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WebApp.Models.ApontamentoProducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraApontamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoParada")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdemProducaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeProduzida")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeRefugo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeRetrabalho")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempoParadoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempoProducaoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempoSetupMinutos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId");

                    b.HasIndex("OrdemProducaoId");

                    b.ToTable("ApontamentosProducao");
                });

            modelBuilder.Entity("WebApp.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ativa");

                    b.HasIndex("Ordem");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9235),
                            Descricao = "Permissões relacionadas à administração do sistema",
                            Nome = "Administração",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9238),
                            Descricao = "Permissões relacionadas ao gerenciamento de usuários",
                            Nome = "Usuários",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9239),
                            Descricao = "Permissões relacionadas ao gerenciamento de clientes",
                            Nome = "Clientes",
                            Ordem = 3
                        },
                        new
                        {
                            Id = 4,
                            Ativa = true,
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9241),
                            Descricao = "Permissões relacionadas à visualização de relatórios",
                            Nome = "Relatórios",
                            Ordem = 4
                        });
                });

            modelBuilder.Entity("WebApp.Models.CategoriaFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CategoriasFinanceiras");
                });

            modelBuilder.Entity("WebApp.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("WebApp.Models.ComponentPaletteModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentPalettes");
                });

            modelBuilder.Entity("WebApp.Models.ContaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Conta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("DigitoVerificador")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ContasBancarias");
                });

            modelBuilder.Entity("WebApp.Models.ContaPagar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaFinanceiraId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContaBancariaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorJuros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorMulta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaFinanceiraId");

                    b.HasIndex("ContaBancariaId");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("FornecedorId");

                    b.ToTable("ContasPagar");
                });

            modelBuilder.Entity("WebApp.Models.ContaReceber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaFinanceiraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContaBancariaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataRecebimento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorJuros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorOriginal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorRecebido")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaFinanceiraId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ContaBancariaId");

                    b.HasIndex("CriadoPorId");

                    b.ToTable("ContasReceber");
                });

            modelBuilder.Entity("WebApp.Models.DiagramModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanvasSettings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Connections")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Diagrams");
                });

            modelBuilder.Entity("WebApp.Models.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CustoMedio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantidadeAtual")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QuantidadeMaxima")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QuantidadeMinima")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("UltimoCusto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Estoques");
                });

            modelBuilder.Entity("WebApp.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contato")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Site")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("WebApp.Models.ItemPedidoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("PedidoCompraId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("QuantidadeRecebida")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("PedidoCompraId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItensPedidoCompra");
                });

            modelBuilder.Entity("WebApp.Models.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("ItensVenda");
                });

            modelBuilder.Entity("WebApp.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AbrirNovaAba")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Controller")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EMenuPai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MenuPaiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("MenuPaiId");

                    b.HasIndex("Ordem");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AbrirNovaAba = false,
                            Action = "Index",
                            Ativo = true,
                            Controller = "Home",
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9198),
                            EMenuPai = false,
                            Icone = "bi-house",
                            Ordem = 1,
                            Titulo = "Home"
                        },
                        new
                        {
                            Id = 2,
                            AbrirNovaAba = false,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9203),
                            EMenuPai = true,
                            Icone = "bi-folder",
                            Ordem = 2,
                            Titulo = "Cadastro"
                        },
                        new
                        {
                            Id = 3,
                            AbrirNovaAba = false,
                            Action = "Index",
                            Ativo = true,
                            Controller = "Cliente",
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9206),
                            EMenuPai = false,
                            Icone = "bi-people",
                            MenuPaiId = 2,
                            Ordem = 1,
                            Titulo = "Cliente"
                        },
                        new
                        {
                            Id = 4,
                            AbrirNovaAba = false,
                            Action = "Privacy",
                            Ativo = true,
                            Controller = "Home",
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9209),
                            EMenuPai = false,
                            Icone = "bi-shield",
                            Ordem = 3,
                            Titulo = "Privacidade"
                        });
                });

            modelBuilder.Entity("WebApp.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CustoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstoqueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrdemProducaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PedidoCompraId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VendaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EstoqueId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MovimentacoesEstoque");
                });

            modelBuilder.Entity("WebApp.Models.MovimentacaoFinanceira", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaFinanceiraId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContaBancariaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContaPagarId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ContaReceberId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaFinanceiraId");

                    b.HasIndex("ContaBancariaId");

                    b.HasIndex("ContaPagarId");

                    b.HasIndex("ContaReceberId");

                    b.HasIndex("CriadoPorId");

                    b.ToTable("MovimentacoesFinanceiras");
                });

            modelBuilder.Entity("WebApp.Models.NFCe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAutorizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<string>("MensagemRetorno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocoloAutorizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEmissao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlConsulta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VendaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Xml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VendaId");

                    b.ToTable("NFCes");
                });

            modelBuilder.Entity("WebApp.Models.OrdemProducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFimPrevista")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFimReal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicioPrevista")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicioReal")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroOrdem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeProduzida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("OrdensProducao");
                });

            modelBuilder.Entity("WebApp.Models.PedidoCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("TEXT");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("FornecedorId");

                    b.ToTable("PedidosCompra");
                });

            modelBuilder.Entity("WebApp.Models.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Controller")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ativa");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Ordem");

                    b.ToTable("Permissoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            CategoriaId = 1,
                            Codigo = "SISTEMA_GERENCIAR",
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9269),
                            Descricao = "Permissão para gerenciar configurações do sistema",
                            Nome = "Gerenciar Sistema",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 2,
                            Action = "Index",
                            Ativa = true,
                            CategoriaId = 1,
                            Codigo = "MENU_GERENCIAR",
                            Controller = "Menu",
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9273),
                            Descricao = "Permissão para gerenciar itens do menu",
                            Nome = "Gerenciar Menu",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            CategoriaId = 2,
                            Codigo = "USUARIO_VISUALIZAR",
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9275),
                            Descricao = "Permissão para visualizar lista de usuários",
                            Nome = "Visualizar Usuários",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 4,
                            Ativa = true,
                            CategoriaId = 2,
                            Codigo = "USUARIO_CRIAR",
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9277),
                            Descricao = "Permissão para criar novos usuários",
                            Nome = "Criar Usuários",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 5,
                            Ativa = true,
                            CategoriaId = 2,
                            Codigo = "USUARIO_EDITAR",
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9278),
                            Descricao = "Permissão para editar usuários existentes",
                            Nome = "Editar Usuários",
                            Ordem = 3
                        },
                        new
                        {
                            Id = 6,
                            Ativa = true,
                            CategoriaId = 2,
                            Codigo = "USUARIO_EXCLUIR",
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9280),
                            Descricao = "Permissão para excluir usuários",
                            Nome = "Excluir Usuários",
                            Ordem = 4
                        },
                        new
                        {
                            Id = 7,
                            Action = "Index",
                            Ativa = true,
                            CategoriaId = 3,
                            Codigo = "CLIENTE_VISUALIZAR",
                            Controller = "Cliente",
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9281),
                            Descricao = "Permissão para visualizar lista de clientes",
                            Nome = "Visualizar Clientes",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 8,
                            Action = "Create",
                            Ativa = true,
                            CategoriaId = 3,
                            Codigo = "CLIENTE_CRIAR",
                            Controller = "Cliente",
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9283),
                            Descricao = "Permissão para criar novos clientes",
                            Nome = "Criar Clientes",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 9,
                            Action = "Edit",
                            Ativa = true,
                            CategoriaId = 3,
                            Codigo = "CLIENTE_EDITAR",
                            Controller = "Cliente",
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9285),
                            Descricao = "Permissão para editar clientes existentes",
                            Nome = "Editar Clientes",
                            Ordem = 3
                        },
                        new
                        {
                            Id = 10,
                            Action = "Delete",
                            Ativa = true,
                            CategoriaId = 3,
                            Codigo = "CLIENTE_EXCLUIR",
                            Controller = "Cliente",
                            DataCriacao = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9287),
                            Descricao = "Permissão para excluir clientes",
                            Nome = "Excluir Clientes",
                            Ordem = 4
                        });
                });

            modelBuilder.Entity("WebApp.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Destaque")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dimensoes")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Peso")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrecoCusto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeMinima")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tamanho")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Destaque");

                    b.HasIndex("Nome");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("WebApp.Models.ProdutoImagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Principal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ordem");

                    b.HasIndex("Principal");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutoImagens");
                });

            modelBuilder.Entity("WebApp.Models.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CapacidadePorHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustoPorHora")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmManutencao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("WebApp.Models.RecursoAlocado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFimAlocacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicioAlocacao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasPlanejadas")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasUtilizadas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdemProducaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecursoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrdemProducaoId");

                    b.HasIndex("RecursoId");

                    b.ToTable("RecursosAlocados");
                });

            modelBuilder.Entity("WebApp.Models.RelatorioPCP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Agrupamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("CamposSelecionados")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfiguracaoJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Filtros")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ordenacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Publico")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoRelatorio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.ToTable("RelatoriosPCP");
                });

            modelBuilder.Entity("WebApp.Models.Sprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Objetivo")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VelocidadeAlvo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VelocidadeReal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("WebApp.Models.SprintReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcoesDeImelhoria")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataReview")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Facilitador")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NotaGeral")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Participantes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PontosNegativos")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PontosPositivos")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SprintId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SprintId");

                    b.ToTable("SprintReviews");
                });

            modelBuilder.Entity("WebApp.Models.SqlQueryModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExecutionTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fields")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Having")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Joins")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Limit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Offset")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OrderBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawSql")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResultCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tables")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationErrors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SqlQueries");
                });

            modelBuilder.Entity("WebApp.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimativaHoras")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsavel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TempoGasto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataVencimento");

                    b.HasIndex("Ordem");

                    b.HasIndex("Prioridade");

                    b.HasIndex("Responsavel");

                    b.HasIndex("Status");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("WebApp.Models.TaskUserStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HorasEstimadas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HorasRealizadas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsavel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserStoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserStoryId");

                    b.ToTable("TaskUserStories");
                });

            modelBuilder.Entity("WebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9036),
                            Email = "admin@teste.com",
                            Name = "Administrador",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 17, 21, 53, 11, 79, DateTimeKind.Local).AddTicks(9039),
                            Email = "usuario@teste.com",
                            Name = "Usuário Teste",
                            Password = "123456"
                        });
                });

            modelBuilder.Entity("WebApp.Models.UserStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CriteriosAceitacao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Epic")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsavel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SprintId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StoryPoints")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SprintId");

                    b.ToTable("UserStories");
                });

            modelBuilder.Entity("WebApp.Models.UsuarioPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Concedida")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataConcessao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("TEXT");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PermissaoId");

                    b.HasIndex("UsuarioId", "PermissaoId")
                        .IsUnique();

                    b.ToTable("UsuarioPermissoes");
                });

            modelBuilder.Entity("WebApp.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChaveAcessoNFCe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataEmissaoNFCe")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NFCeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroNFCe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PossuiNFCe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerieNFCe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusNFCe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NFCeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("WebApp.Models.WhatsAppIntegracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenAcesso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WhatsAppIntegracoes");
                });

            modelBuilder.Entity("WebApp.Models.ApontamentoProducao", b =>
                {
                    b.HasOne("WebApp.Models.User", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId");

                    b.HasOne("WebApp.Models.OrdemProducao", "OrdemProducao")
                        .WithMany("Apontamentos")
                        .HasForeignKey("OrdemProducaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operador");

                    b.Navigation("OrdemProducao");
                });

            modelBuilder.Entity("WebApp.Models.ContaPagar", b =>
                {
                    b.HasOne("WebApp.Models.CategoriaFinanceira", "CategoriaFinanceira")
                        .WithMany("ContasPagar")
                        .HasForeignKey("CategoriaFinanceiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.ContaBancaria", "ContaBancaria")
                        .WithMany("ContasPagar")
                        .HasForeignKey("ContaBancariaId");

                    b.HasOne("WebApp.Models.User", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Fornecedor", "Fornecedor")
                        .WithMany("ContasPagar")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaFinanceira");

                    b.Navigation("ContaBancaria");

                    b.Navigation("CriadoPor");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("WebApp.Models.ContaReceber", b =>
                {
                    b.HasOne("WebApp.Models.CategoriaFinanceira", "CategoriaFinanceira")
                        .WithMany("ContasReceber")
                        .HasForeignKey("CategoriaFinanceiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Cliente", "Cliente")
                        .WithMany("ContasReceber")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.ContaBancaria", "ContaBancaria")
                        .WithMany("ContasReceber")
                        .HasForeignKey("ContaBancariaId");

                    b.HasOne("WebApp.Models.User", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaFinanceira");

                    b.Navigation("Cliente");

                    b.Navigation("ContaBancaria");

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("WebApp.Models.Estoque", b =>
                {
                    b.HasOne("WebApp.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("WebApp.Models.ItemPedidoCompra", b =>
                {
                    b.HasOne("WebApp.Models.PedidoCompra", "PedidoCompra")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoCompra");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("WebApp.Models.ItemVenda", b =>
                {
                    b.HasOne("WebApp.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("WebApp.Models.MenuItem", b =>
                {
                    b.HasOne("WebApp.Models.MenuItem", "MenuPai")
                        .WithMany("SubMenus")
                        .HasForeignKey("MenuPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MenuPai");
                });

            modelBuilder.Entity("WebApp.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("WebApp.Models.Estoque", "Estoque")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("EstoqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estoque");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApp.Models.MovimentacaoFinanceira", b =>
                {
                    b.HasOne("WebApp.Models.CategoriaFinanceira", "CategoriaFinanceira")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("CategoriaFinanceiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.ContaBancaria", "ContaBancaria")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.ContaPagar", "ContaPagar")
                        .WithMany()
                        .HasForeignKey("ContaPagarId");

                    b.HasOne("WebApp.Models.ContaReceber", "ContaReceber")
                        .WithMany()
                        .HasForeignKey("ContaReceberId");

                    b.HasOne("WebApp.Models.User", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaFinanceira");

                    b.Navigation("ContaBancaria");

                    b.Navigation("ContaPagar");

                    b.Navigation("ContaReceber");

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("WebApp.Models.NFCe", b =>
                {
                    b.HasOne("WebApp.Models.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("WebApp.Models.OrdemProducao", b =>
                {
                    b.HasOne("WebApp.Models.User", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId");

                    b.HasOne("WebApp.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriadoPor");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("WebApp.Models.PedidoCompra", b =>
                {
                    b.HasOne("WebApp.Models.User", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Fornecedor", "Fornecedor")
                        .WithMany("PedidosCompra")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriadoPor");

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("WebApp.Models.Permissao", b =>
                {
                    b.HasOne("WebApp.Models.Categoria", "Categoria")
                        .WithMany("Permissoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("WebApp.Models.Produto", b =>
                {
                    b.HasOne("WebApp.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("WebApp.Models.ProdutoImagem", b =>
                {
                    b.HasOne("WebApp.Models.Produto", "Produto")
                        .WithMany("Imagens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("WebApp.Models.RecursoAlocado", b =>
                {
                    b.HasOne("WebApp.Models.OrdemProducao", "OrdemProducao")
                        .WithMany("RecursosAlocados")
                        .HasForeignKey("OrdemProducaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Recurso", "Recurso")
                        .WithMany("Alocacoes")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemProducao");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("WebApp.Models.RelatorioPCP", b =>
                {
                    b.HasOne("WebApp.Models.User", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("WebApp.Models.SprintReview", b =>
                {
                    b.HasOne("WebApp.Models.Sprint", "Sprint")
                        .WithMany("Reviews")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("WebApp.Models.TaskUserStory", b =>
                {
                    b.HasOne("WebApp.Models.UserStory", "UserStory")
                        .WithMany("Tasks")
                        .HasForeignKey("UserStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserStory");
                });

            modelBuilder.Entity("WebApp.Models.UserStory", b =>
                {
                    b.HasOne("WebApp.Models.Sprint", "Sprint")
                        .WithMany("UserStories")
                        .HasForeignKey("SprintId");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("WebApp.Models.UsuarioPermissao", b =>
                {
                    b.HasOne("WebApp.Models.Permissao", "Permissao")
                        .WithMany("UsuarioPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.User", "Usuario")
                        .WithMany("UsuarioPermissoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApp.Models.Venda", b =>
                {
                    b.HasOne("WebApp.Models.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("ClienteId");

                    b.HasOne("WebApp.Models.NFCe", "NFCe")
                        .WithMany()
                        .HasForeignKey("NFCeId");

                    b.HasOne("WebApp.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("NFCe");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApp.Models.Categoria", b =>
                {
                    b.Navigation("Permissoes");
                });

            modelBuilder.Entity("WebApp.Models.CategoriaFinanceira", b =>
                {
                    b.Navigation("ContasPagar");

                    b.Navigation("ContasReceber");

                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("WebApp.Models.Cliente", b =>
                {
                    b.Navigation("ContasReceber");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("WebApp.Models.ContaBancaria", b =>
                {
                    b.Navigation("ContasPagar");

                    b.Navigation("ContasReceber");

                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("WebApp.Models.Estoque", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("WebApp.Models.Fornecedor", b =>
                {
                    b.Navigation("ContasPagar");

                    b.Navigation("PedidosCompra");
                });

            modelBuilder.Entity("WebApp.Models.MenuItem", b =>
                {
                    b.Navigation("SubMenus");
                });

            modelBuilder.Entity("WebApp.Models.OrdemProducao", b =>
                {
                    b.Navigation("Apontamentos");

                    b.Navigation("RecursosAlocados");
                });

            modelBuilder.Entity("WebApp.Models.PedidoCompra", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("WebApp.Models.Permissao", b =>
                {
                    b.Navigation("UsuarioPermissoes");
                });

            modelBuilder.Entity("WebApp.Models.Produto", b =>
                {
                    b.Navigation("Imagens");
                });

            modelBuilder.Entity("WebApp.Models.Recurso", b =>
                {
                    b.Navigation("Alocacoes");
                });

            modelBuilder.Entity("WebApp.Models.Sprint", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("UserStories");
                });

            modelBuilder.Entity("WebApp.Models.User", b =>
                {
                    b.Navigation("UsuarioPermissoes");
                });

            modelBuilder.Entity("WebApp.Models.UserStory", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("WebApp.Models.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
