// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251107113308_AddModuloPCP")]
    partial class AddModuloPCP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WebApp.Models.ApontamentoProducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraApontamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoParada")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OperadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdemProducaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeProduzida")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeRefugo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeRetrabalho")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempoParadoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempoProducaoMinutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempoSetupMinutos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId");

                    b.HasIndex("OrdemProducaoId");

                    b.ToTable("ApontamentosProducao");
                });

            modelBuilder.Entity("WebApp.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ativa");

                    b.HasIndex("Ordem");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8534),
                            Descricao = "Permissões relacionadas à administração do sistema",
                            Nome = "Administração",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 2,
                            Ativa = true,
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8537),
                            Descricao = "Permissões relacionadas ao gerenciamento de usuários",
                            Nome = "Usuários",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8538),
                            Descricao = "Permissões relacionadas ao gerenciamento de clientes",
                            Nome = "Clientes",
                            Ordem = 3
                        },
                        new
                        {
                            Id = 4,
                            Ativa = true,
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8541),
                            Descricao = "Permissões relacionadas à visualização de relatórios",
                            Nome = "Relatórios",
                            Ordem = 4
                        });
                });

            modelBuilder.Entity("WebApp.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("WebApp.Models.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("ItensVenda");
                });

            modelBuilder.Entity("WebApp.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AbrirNovaAba")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Area")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Controller")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EMenuPai")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MenuPaiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("MenuPaiId");

                    b.HasIndex("Ordem");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AbrirNovaAba = false,
                            Action = "Index",
                            Ativo = true,
                            Controller = "Home",
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8493),
                            EMenuPai = false,
                            Icone = "bi-house",
                            Ordem = 1,
                            Titulo = "Home"
                        },
                        new
                        {
                            Id = 2,
                            AbrirNovaAba = false,
                            Ativo = true,
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8498),
                            EMenuPai = true,
                            Icone = "bi-folder",
                            Ordem = 2,
                            Titulo = "Cadastro"
                        },
                        new
                        {
                            Id = 3,
                            AbrirNovaAba = false,
                            Action = "Index",
                            Ativo = true,
                            Controller = "Cliente",
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8502),
                            EMenuPai = false,
                            Icone = "bi-people",
                            MenuPaiId = 2,
                            Ordem = 1,
                            Titulo = "Cliente"
                        },
                        new
                        {
                            Id = 4,
                            AbrirNovaAba = false,
                            Action = "Privacy",
                            Ativo = true,
                            Controller = "Home",
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8504),
                            EMenuPai = false,
                            Icone = "bi-shield",
                            Ordem = 3,
                            Titulo = "Privacidade"
                        });
                });

            modelBuilder.Entity("WebApp.Models.NFCe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAutorizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<string>("MensagemRetorno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocoloAutorizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEmissao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlConsulta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VendaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Xml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VendaId");

                    b.ToTable("NFCes");
                });

            modelBuilder.Entity("WebApp.Models.OrdemProducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CriadoPorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFimPrevista")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFimReal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicioPrevista")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicioReal")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroOrdem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantidadeProduzida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("OrdensProducao");
                });

            modelBuilder.Entity("WebApp.Models.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Controller")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Ativa");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Ordem");

                    b.ToTable("Permissoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ativa = true,
                            CategoriaId = 1,
                            Codigo = "SISTEMA_GERENCIAR",
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8577),
                            Descricao = "Permissão para gerenciar configurações do sistema",
                            Nome = "Gerenciar Sistema",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 2,
                            Action = "Index",
                            Ativa = true,
                            CategoriaId = 1,
                            Codigo = "MENU_GERENCIAR",
                            Controller = "Menu",
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8585),
                            Descricao = "Permissão para gerenciar itens do menu",
                            Nome = "Gerenciar Menu",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 3,
                            Ativa = true,
                            CategoriaId = 2,
                            Codigo = "USUARIO_VISUALIZAR",
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8587),
                            Descricao = "Permissão para visualizar lista de usuários",
                            Nome = "Visualizar Usuários",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 4,
                            Ativa = true,
                            CategoriaId = 2,
                            Codigo = "USUARIO_CRIAR",
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8589),
                            Descricao = "Permissão para criar novos usuários",
                            Nome = "Criar Usuários",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 5,
                            Ativa = true,
                            CategoriaId = 2,
                            Codigo = "USUARIO_EDITAR",
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8591),
                            Descricao = "Permissão para editar usuários existentes",
                            Nome = "Editar Usuários",
                            Ordem = 3
                        },
                        new
                        {
                            Id = 6,
                            Ativa = true,
                            CategoriaId = 2,
                            Codigo = "USUARIO_EXCLUIR",
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8593),
                            Descricao = "Permissão para excluir usuários",
                            Nome = "Excluir Usuários",
                            Ordem = 4
                        },
                        new
                        {
                            Id = 7,
                            Action = "Index",
                            Ativa = true,
                            CategoriaId = 3,
                            Codigo = "CLIENTE_VISUALIZAR",
                            Controller = "Cliente",
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8595),
                            Descricao = "Permissão para visualizar lista de clientes",
                            Nome = "Visualizar Clientes",
                            Ordem = 1
                        },
                        new
                        {
                            Id = 8,
                            Action = "Create",
                            Ativa = true,
                            CategoriaId = 3,
                            Codigo = "CLIENTE_CRIAR",
                            Controller = "Cliente",
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8597),
                            Descricao = "Permissão para criar novos clientes",
                            Nome = "Criar Clientes",
                            Ordem = 2
                        },
                        new
                        {
                            Id = 9,
                            Action = "Edit",
                            Ativa = true,
                            CategoriaId = 3,
                            Codigo = "CLIENTE_EDITAR",
                            Controller = "Cliente",
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8599),
                            Descricao = "Permissão para editar clientes existentes",
                            Nome = "Editar Clientes",
                            Ordem = 3
                        },
                        new
                        {
                            Id = 10,
                            Action = "Delete",
                            Ativa = true,
                            CategoriaId = 3,
                            Codigo = "CLIENTE_EXCLUIR",
                            Controller = "Cliente",
                            DataCriacao = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8601),
                            Descricao = "Permissão para excluir clientes",
                            Nome = "Excluir Clientes",
                            Ordem = 4
                        });
                });

            modelBuilder.Entity("WebApp.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Destaque")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dimensoes")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Peso")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PrecoCusto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuantidadeMinima")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tamanho")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Destaque");

                    b.HasIndex("Nome");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("WebApp.Models.ProdutoImagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Principal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ordem");

                    b.HasIndex("Principal");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutoImagens");
                });

            modelBuilder.Entity("WebApp.Models.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CapacidadePorHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CustoPorHora")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmManutencao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("WebApp.Models.RecursoAlocado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataFimAlocacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicioAlocacao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasPlanejadas")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HorasUtilizadas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdemProducaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecursoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrdemProducaoId");

                    b.HasIndex("RecursoId");

                    b.ToTable("RecursosAlocados");
                });

            modelBuilder.Entity("WebApp.Models.RelatorioPCP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Agrupamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("CamposSelecionados")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfiguracaoJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Filtros")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ordenacao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Publico")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoRelatorio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorId");

                    b.ToTable("RelatoriosPCP");
                });

            modelBuilder.Entity("WebApp.Models.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EstimativaHoras")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsavel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TempoGasto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataVencimento");

                    b.HasIndex("Ordem");

                    b.HasIndex("Prioridade");

                    b.HasIndex("Responsavel");

                    b.HasIndex("Status");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("WebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8208),
                            Email = "admin@teste.com",
                            Name = "Administrador",
                            Password = "123456"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 7, 8, 33, 7, 665, DateTimeKind.Local).AddTicks(8211),
                            Email = "usuario@teste.com",
                            Name = "Usuário Teste",
                            Password = "123456"
                        });
                });

            modelBuilder.Entity("WebApp.Models.UsuarioPermissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comentario")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Concedida")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataConcessao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataExpiracao")
                        .HasColumnType("TEXT");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PermissaoId");

                    b.HasIndex("UsuarioId", "PermissaoId")
                        .IsUnique();

                    b.ToTable("UsuarioPermissoes");
                });

            modelBuilder.Entity("WebApp.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChaveAcessoNFCe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DataEmissaoNFCe")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NFCeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroNFCe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PossuiNFCe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerieNFCe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusNFCe")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NFCeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("WebApp.Models.WhatsAppIntegracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenAcesso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WhatsAppIntegracoes");
                });

            modelBuilder.Entity("WebApp.Models.ApontamentoProducao", b =>
                {
                    b.HasOne("WebApp.Models.User", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId");

                    b.HasOne("WebApp.Models.OrdemProducao", "OrdemProducao")
                        .WithMany("Apontamentos")
                        .HasForeignKey("OrdemProducaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operador");

                    b.Navigation("OrdemProducao");
                });

            modelBuilder.Entity("WebApp.Models.ItemVenda", b =>
                {
                    b.HasOne("WebApp.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("WebApp.Models.MenuItem", b =>
                {
                    b.HasOne("WebApp.Models.MenuItem", "MenuPai")
                        .WithMany("SubMenus")
                        .HasForeignKey("MenuPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MenuPai");
                });

            modelBuilder.Entity("WebApp.Models.NFCe", b =>
                {
                    b.HasOne("WebApp.Models.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("WebApp.Models.OrdemProducao", b =>
                {
                    b.HasOne("WebApp.Models.User", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId");

                    b.HasOne("WebApp.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriadoPor");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("WebApp.Models.Permissao", b =>
                {
                    b.HasOne("WebApp.Models.Categoria", "Categoria")
                        .WithMany("Permissoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("WebApp.Models.Produto", b =>
                {
                    b.HasOne("WebApp.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("WebApp.Models.ProdutoImagem", b =>
                {
                    b.HasOne("WebApp.Models.Produto", "Produto")
                        .WithMany("Imagens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("WebApp.Models.RecursoAlocado", b =>
                {
                    b.HasOne("WebApp.Models.OrdemProducao", "OrdemProducao")
                        .WithMany("RecursosAlocados")
                        .HasForeignKey("OrdemProducaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Recurso", "Recurso")
                        .WithMany("Alocacoes")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemProducao");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("WebApp.Models.RelatorioPCP", b =>
                {
                    b.HasOne("WebApp.Models.User", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CriadoPor");
                });

            modelBuilder.Entity("WebApp.Models.UsuarioPermissao", b =>
                {
                    b.HasOne("WebApp.Models.Permissao", "Permissao")
                        .WithMany("UsuarioPermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.User", "Usuario")
                        .WithMany("UsuarioPermissoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApp.Models.Venda", b =>
                {
                    b.HasOne("WebApp.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("WebApp.Models.NFCe", "NFCe")
                        .WithMany()
                        .HasForeignKey("NFCeId");

                    b.HasOne("WebApp.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("NFCe");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApp.Models.Categoria", b =>
                {
                    b.Navigation("Permissoes");
                });

            modelBuilder.Entity("WebApp.Models.MenuItem", b =>
                {
                    b.Navigation("SubMenus");
                });

            modelBuilder.Entity("WebApp.Models.OrdemProducao", b =>
                {
                    b.Navigation("Apontamentos");

                    b.Navigation("RecursosAlocados");
                });

            modelBuilder.Entity("WebApp.Models.Permissao", b =>
                {
                    b.Navigation("UsuarioPermissoes");
                });

            modelBuilder.Entity("WebApp.Models.Produto", b =>
                {
                    b.Navigation("Imagens");
                });

            modelBuilder.Entity("WebApp.Models.Recurso", b =>
                {
                    b.Navigation("Alocacoes");
                });

            modelBuilder.Entity("WebApp.Models.User", b =>
                {
                    b.Navigation("UsuarioPermissoes");
                });

            modelBuilder.Entity("WebApp.Models.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
