// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

namespace WebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251025000000_AddWhatsAppIntegracao")]
    partial class AddWhatsAppIntegracao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            // Outros modelos existentes...

            modelBuilder.Entity("WebApp.Models.WhatsAppIntegracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroTelefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenAcesso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WhatsAppIntegracoes");
                });
#pragma warning restore 612, 618
        }
    }
}